name: "Pull Request Labeler"
on:
  workflow_dispatch:

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: thomasjpfan/labeler@v2.5.0
      continue-on-error: true
      if: github.repository == 'scikit-learn/scikit-learn'
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        max-labels: "3"
        configuration-path: ".github/labeler-module.yml"

  triage_file_extensions:
    runs-on: ubuntu-latest
    steps:
    - uses: thomasjpfan/labeler@v2.5.0
      continue-on-error: true
      if: github.repository == 'scikit-learn/scikit-learn'
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: ".github/labeler-file-extensions.yml"
